// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Game        string
	GamePlayers string
	GameRounds  string
	Users       string
}{
	Game:        "game",
	GamePlayers: "game_players",
	GameRounds:  "game_rounds",
	Users:       "users",
}
